# Generated by Django 4.1.3 on 2022-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedInUrl', models.URLField(blank=True, null=True)),
                ('hackerrankUrl', models.URLField(blank=True, null=True)),
                ('leetcodeUrl', models.URLField(blank=True, null=True)),
                ('youtubeUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('pImg', models.ImageField(upload_to='media')),
                ('pDesc', models.TextField(blank=True, null=True)),
                ('pUrl', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
