# Generated by Django 4.1.3 on 2022-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_myphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xyz', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
