# Generated by Django 4.1.3 on 2022-12-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
