# Generated by Django 4.1.3 on 2022-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
