# Generated by Django 4.1.3 on 2022-12-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0009_contactinfo_link1_contactinfo_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='githubUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
