# Generated by Django 4.1.3 on 2022-12-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0011_contactinfo_emailimg_contactinfo_githuburlimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='emailImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='githubUrlImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='hackerrankUrlImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='leetcodeUrlImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link1Img',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link2Img',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedInUrlImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phoneImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtubeUrlImg',
            field=models.FileField(blank=True, null=True, upload_to='contacts'),
        ),
    ]
